auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    chunks_directory: /loki/chunks
    rules_directory: /loki/rules

tsdb_shipper:
  active_index_directory: /loki/index
  cache_location: /loki/index_cache

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true

limits_config:
  retention_period: 168h
  allow_structured_metadata: false

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
  enable_alertmanager_v2: true

common:
  path_prefix: /loki
  replication_factor: 1
