_format_version: "3.0"
_transform: true

services:
  - name: crapi-backend
    url: https://crapi-web:443
    routes:
      # 1. Luồng không bảo vệ (Cho phép tải giao diện Web HTML/CSS/JS)
      - name: public-frontend
        paths:
          - /identity/api/auth
          - /
        strip_path: false

      # 2. Luồng bảo mật nghiêm ngặt (Chỉ cho phép API đi qua nếu có Token)
      - name: secure-api
        paths:
          - /workshop/api
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 60
              hour: 1000
              limit_by: ip
              policy: local
plugins:
  - name: correlation-id
    config:
      header_name: X-Request-ID
      generator: uuid
      echo_downstream: true

consumers:
  - username: crapi-identity-issuer

jwt_secrets:
  - consumer: crapi-identity-issuer
    key: MKMZkDenUfuDF2byYowDj7tW5Ox6XG4Y1THTEGScRg8
    algorithm: RS256
    rsa_public_key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsZKrGYja9S7BkO+waOcu
      poGY6BQjixJkg1Uitt278NbiCSnBRw5/cmfuWFFFPgRxabBZBJwJAujnQrlgTLXn
      RRItM9SRO884cEXn+s4Uc8qwk6pev63qb8no6aCVY0dFpthEGtOP+3KIJ2kx2i5H
      Nzm8d7fG3ZswZrttDVbSSTy8UjPTOr4xVw1Yyh/GzGK9i/RYBWHftDsVfKrHcgGn
      1F/T6W0cgcnh4KFmbyOQ7dUy8Uc6Gu8JHeHJVt2vGcn50EDtUy2YN+UnZPjCSC7v
      YOfd5teUR/Bf4jg8GN6UnLbr/Et8HUnz9RFBLkPIf0NiY6iRjp9ooSDkml2OGql3
      wwIDAQAB
      -----END PUBLIC KEY-----